# 📊 Part 2: Working with Data (Pandas as SQL)

Now that we know the basic building blocks, let's introduce **Pandas**.
Pandas is the standard data manipulation library in Python. It allows us to work with data in a tabular format (rows and columns), just like a SQL database.

In this notebook, we will translate your SQL vocabulary directly into Python Pandas syntax!

In [ ]:
import pandas as pd
import seaborn as sns

# Load a real public dataset: 'tips'
# This contains data about restaurant bills, tips, and customer demographics
df = sns.load_dataset('tips')

print("Table 'df' (Tips Dataset) loaded successfully!")
display(df.head())

Table 'df' (Tips Dataset) loaded successfully!

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

### 1. `SELECT *` (Inspecting Data)
**SQL:** `SELECT * FROM tips LIMIT 5;`

**Pandas:** `.head()` and `.info()`

In [ ]:
# EXAMPLE: View the first 5 rows and check schema
display(df.head(5))
df.info()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB

### 2. Selecting Columns & Aggregates (`SELECT col`)
**SQL:** `SELECT total_bill, tip FROM tips;` | `SELECT MAX(total_bill) FROM tips;`

**Pandas:** `df[['col1', 'col2']]`

**Example:**

In [ ]:
# SELECT day, time FROM df LIMIT 3;
subset = df[['day', 'time']]
display(subset.head(3))

# SELECT MAX(total_bill) FROM df;
max_bill = df['total_bill'].max()
print(f"\nThe maximum bill amount is: ${max_bill}")

   day    time
0  Sun  Dinner
1  Sun  Dinner
2  Sun  Dinner

The maximum bill amount is: $50.81

#### ✍️ Practice 1: Selecting Columns
**Task:** Select the `sex`, `smoker`, and `tip` columns from the dataframe. Also, find the **minimum** value of the `tip` column.

In [ ]:
# Your code here:

### 3. Filtering Data (`WHERE`)
**SQL:** `SELECT * FROM tips WHERE day = 'Sun' AND total_bill > 20;`

**Pandas:** `df[(df['col'] == 'val')]`

**Example:**

In [ ]:
# SELECT * FROM df WHERE size > 4 OR smoker = 'Yes';
filtered_df = df[(df['size'] > 4) | (df['smoker'] == 'Yes')]
display(filtered_df.head(100))

     total_bill   tip     sex smoker  day    time  size
56        38.01  3.00    Male    Yes  Sat  Dinner     4
58        11.24  1.76    Male    Yes  Sat  Dinner     2
60        20.29  3.21    Male    Yes  Sat  Dinner     2
61        13.81  2.00    Male    Yes  Sat  Dinner     2
62        11.02  1.98    Male    Yes  Sat  Dinner     2
..          ...   ...     ...    ...  ...     ...   ...
234       15.53  3.00    Male    Yes  Sat  Dinner     2
236       12.60  1.00    Male    Yes  Sat  Dinner     2
237       32.83  1.17    Male    Yes  Sat  Dinner     2
240       27.18  2.00  Female    Yes  Sat  Dinner     2
241       22.67  2.00    Male    Yes  Sat  Dinner     2

[100 rows x 7 columns]

#### ✍️ Practice 2: Filtering
**Task:** Filter the dataset to show only rows where the `time` is 'Lunch' AND the `sex` is 'Female'.

In [ ]:
# Your code here:

### 4. Aggregations & Sorting (`GROUP BY` & `ORDER BY`)
**SQL:** `SELECT time, SUM(total_bill) FROM tips GROUP BY time ORDER BY SUM(total_bill) DESC;`

**Example:**

In [ ]:
# Grouping, aggregating, and sorting
# We add observed=False to handle categorical data and remove the warning
revenue_by_time = df.groupby('time', observed=False)['total_bill'].sum().sort_values(ascending=False)
display(revenue_by_time)

time
Dinner    3660.30
Lunch     1167.47
Name: total_bill, dtype: float64

#### ✍️ Practice 3: Aggregation
**Task:** Group the data by `day`, calculate the **average** (mean) `tip` for each day, and sort the results from highest to lowest.

In [ ]:
# Your code here:

### 5. Calculated Columns & Exporting
**SQL:** `SELECT *, (tip/total_bill)*100 AS tip_percentage FROM tips;`

**Pandas:** `df['new_col'] = ...`

**Example:**

In [ ]:
# Creating a new computed column: Tip Percentage
df['tip_percentage'] = (df['tip'] / df['total_bill']) * 100

# Let's check the new column
display(df[['total_bill', 'tip', 'tip_percentage']].head())

# Exporting to CSV
df.to_csv('processed_tips.csv', index=False)
print("\nData successfully exported to 'processed_tips.csv'!")

   total_bill   tip  tip_percentage
0       16.99  1.01        5.944673
1       10.34  1.66       16.054159
2       21.01  3.50       16.658734
3       23.68  3.31       13.978041
4       24.59  3.61       14.680765

Data successfully exported to 'processed_tips.csv'!

### 6. Joining Data (`JOIN`)
**SQL:** `SELECT * FROM tips LEFT JOIN staff ON tips.day = staff.day;`

**Pandas:** `pd.merge(df1, df2, on='key', how='inner|left|right|outer')`

**Example (Different Join Types):**

In [ ]:
# 1. Create staff data
staff_data = pd.DataFrame({
    'day': ['Thur', 'Fri', 'Sat', 'Sun', 'Mon'], # Mon is extra
    'manager': ['Alice', 'Bob', 'Charlie', 'David', 'Eve']
})

display(staff_data)

# 2. Left Join (Keep all rows from 'tips')
left_join = pd.merge(df, staff_data, on='day', how='left')

# 3. Outer Join (Keep everything from both, filling NaNs where no match)
outer_join = pd.merge(df, staff_data, on='day', how='outer')

print("Left Join result (First 5 rows):")
display(left_join.head())

print("\nCheck the unique managers in Outer Join (includes Eve):")
print(outer_join['manager'].unique())

    day  manager
0  Thur    Alice
1   Fri      Bob
2   Sat  Charlie
3   Sun    David
4   Mon      Eve

Left Join result (First 5 rows):

   total_bill   tip     sex smoker  day    time  size  tip_percentage manager
0       16.99  1.01  Female     No  Sun  Dinner     2        5.944673   David
1       10.34  1.66    Male     No  Sun  Dinner     3       16.054159   David
2       21.01  3.50    Male     No  Sun  Dinner     3       16.658734   David
3       23.68  3.31    Male     No  Sun  Dinner     2       13.978041   David
4       24.59  3.61  Female     No  Sun  Dinner     4       14.680765   David

Check the unique managers in Outer Join (includes Eve):
['Bob' 'Eve' 'Charlie' 'David' 'Alice']

In [ ]:
set(df['day'])

{'Fri', 'Sat', 'Sun', 'Thur'}

#### ✍️ Practice 4: Different Join Types
**Task:** Create a DataFrame `shift_notes` with `day` and `note` (e.g., 'Busy', 'Slow'). Try performing a **Right Join** with the original `df` on the `day` column and observe how it differs from an Inner join.

In [ ]:
# Your code here: